# Generated by Django 6.0 on 2025-12-07 17:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('reporter_name', models.CharField(max_length=100)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('Under Review', 'Under Review'), ('Fixed', 'Fixed')], default='Reported', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='StreetlightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_type', models.CharField(choices=[('Out', 'Out'), ('Flickering', 'Flickering'), ('Broken Fixture', 'Broken Fixture')], max_length=50)),
                ('pole_id', models.CharField(blank=True, max_length=50, null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('Inspected', 'Inspected'), ('Repaired', 'Repaired')], default='Reported', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
