# Generated by Django 6.0 on 2026-02-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_subcounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='potholereport',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.subcounty'),
        ),
        migrations.AddField(
            model_name='streetlightreport',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.subcounty'),
        ),
    ]
