# Generated by Django 6.0 on 2026-02-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_potholereport_sub_county_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcounty',
            options={},
        ),
        migrations.RenameField(
            model_name='potholereport',
            old_name='report_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='streetlightreport',
            name='pole_id',
        ),
        migrations.RemoveField(
            model_name='streetlightreport',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='streetlightreport',
            name='sub_county',
        ),
        migrations.AddField(
            model_name='potholereport',
            name='sub_county_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='streetlightreport',
            name='sub_county_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='potholereport',
            name='severity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='potholereport',
            name='status',
            field=models.CharField(default='Reported', max_length=20),
        ),
        migrations.AlterField(
            model_name='streetlightreport',
            name='light_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='streetlightreport',
            name='status',
            field=models.CharField(default='Reported', max_length=20),
        ),
    ]
