# Generated by Django 6.0 on 2026-02-17 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_subcounty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetlightreport',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.subcounty'),
        ),
    ]
