# Generated by Django 6.0 on 2026-02-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_streetlightreport_sub_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='potholereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='potholes/'),
        ),
        migrations.AddField(
            model_name='streetlightreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Streetlight/'),
        ),
    ]
