# Generated by Django 6.0 on 2026-02-23 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_potholereport_image_streetlightreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetlightreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streetlightreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='streetlights/'),
        ),
    ]
